'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';
const inter = Inter({ subsets: ['latin'] });

const client = new ApolloClient({
    uri: 'http://localhost:3000/api/graphql', // Sunucunuzun URL'si
    cache: new InMemoryCache(),
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                {' '}
                <ApolloProvider client={client}>{children}</ApolloProvider>
            </body>
        </html>
    );
}
